// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaharie_Alexandra_Proiect4.Data;

#nullable disable

namespace Zaharie_Alexandra_Proiect4.Migrations
{
    [DbContext(typeof(Zaharie_Alexandra_Proiect4Context))]
    [Migration("20240217205417_Language")]
    partial class Language
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int?>("MentorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("MentorID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.CourseDepartment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("CourseDepartment");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Mentor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MentorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mentor");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Course", b =>
                {
                    b.HasOne("Zaharie_Alexandra_Proiect4.Models.Language", null)
                        .WithMany("Courses")
                        .HasForeignKey("LanguageID");

                    b.HasOne("Zaharie_Alexandra_Proiect4.Models.Mentor", "Mentor")
                        .WithMany("Courses")
                        .HasForeignKey("MentorID");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.CourseDepartment", b =>
                {
                    b.HasOne("Zaharie_Alexandra_Proiect4.Models.Course", "Course")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zaharie_Alexandra_Proiect4.Models.Department", "Department")
                        .WithMany("CourseDepartment")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Course", b =>
                {
                    b.Navigation("CourseDepartments");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Department", b =>
                {
                    b.Navigation("CourseDepartment");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Language", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Zaharie_Alexandra_Proiect4.Models.Mentor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
